#!/usr/bin/perl -l
##
## Adds text to each line from stdin.
## Copyright (c) 2005 by Stanislaw Klekot (dozzie/AT/irc.pl)
##
## This software is OSI Certified Open Source Software.
## OSI Certified is a certification mark of the Open Source Initiative.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

# Script adds text from command line to end (or beginning, if specified) of
# each line from standard input.
#
# $ printf "123\n321\n***\n" | add aaaaaa
# results in
# > 123aaaaaa
# > 321aaaaaa
# > ***aaaaaa

if (!@ARGV || $ARGV[0] eq "--help" || $ARGV[0] eq "-h") {
  $0 =~ s{.*/}{};
  print "Usage: $0 [-b | --begin | -s | --start] [--] text to add";
  exit;
}

%arg = qw/-b 1 --begin 1 -s 1 --start 1/;

if (exists $arg{$ARGV[0]}) {
  shift;
  shift if $ARGV[0] eq "--";
  $all = "@ARGV";

  while (<STDIN>) {
    chomp;
    print $all, $_;
  }
  exit;
}

shift if $ARGV[0] eq "--";
$all = "@ARGV";

while (<STDIN>) {
  chomp;
  print $_, $all;
}
