#!/usr/bin/perl -l
##
## Adds text to each line from stdin.
## $Id: add,v 1.3 2005/07/11 00:20:58 mina86 Exp $
## Copyright (c) 2005 by Stanislaw Klekot (dozzie/AT/irc.pl)
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##

# Script adds text from command line to end (or beginning, if specified) of
# each line from standard input.
#
# $ printf "123\n321\n***\n" | add aaaaaa
# results in
# > 123aaaaaa
# > 321aaaaaa
# > ***aaaaaa

if (!@ARGV || $ARGV[0] eq "--help" || $ARGV[0] eq "-h") {
  $0 =~ s{.*/}{};
  print "Usage: $0 [-b | --begin | -s | --start] [--] text to add"
  exit;
}

%arg = qw/-b 1 --begin 1 -s 1 --start 1/;

if (exists $arg{$ARGV[0]}) {
  shift;

  $all = "@ARGV";

  while (<STDIN>) {
    chomp;
    print $all, $_;
  }
  exit;
}

shift if $ARGV[0] eq "--";

while (<STDIN>) {
  chomp;
  print $_, $all;
}
