#!/usr/bin/perl -lw
##
## Checks mboxes for unread mail.
## $Id: checkmail,v 1.4 2008/11/08 23:45:57 mina86 Exp $
## Copyright (c) 2005 by Stanislaw Klekot (dozzie/AT/irc.pl)
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

# Script checks if specified mailboxes (mbox format) contain not yet read
# mail. Not read mail is such that doesn't have "Status:" header or has "O"
# there.
#
# Invokation: $0 mailbox ...

MAILBOX: foreach $mailbox (@ARGV) {
  open MAIL, $mailbox or do {
    print STDERR "Can't open mailbox: $!";
    next MAILBOX;
  };

  until (eof MAIL) {
    $status = "";

    do {
      chomp($_ = <MAIL>);
      $status  = $1 if /^status:\s*(.*)/i;
    } while ($_ ne "");

    if ($status eq "O" || $status eq "") {
      $mailbox =~ s{^.*/}{};
      print "You have mail in $mailbox";
      next MAILBOX;
    }

    do { $_ = <MAIL> } until eof MAIL || /^From .* [A-Z][a-z][a-z] [A-Z][a-z][a-z] \d\d \d\d:\d\d:\d\d \d\d\d\d\s?$/;
  }

  close MAIL;
}
