#!/bin/bash
##
## Downlaods MKS-Vir virus database.
## $Id: get_mks_vir_bases,v 1.4 2008/11/08 23:45:57 mina86 Exp $
## Copyright (c) 2005 by Stanislaw Klekot (dozzie/AT/irc.pl)
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

if [ $# = 0 -o ! -d "$1" ]; then
  echo "Usage: ${0##*/} directory_for_bases"
  exit
fi

#-----------------------------------------------------------------------------

LINK=http://download.mks.com.pl/download/linux/bazy.link

#-----------------------------------------------------------------------------

# finish whole script if any error occurs
set -e

cd "$1"
mkdir tmp
cd tmp

wget "$LINK"
LINK2=`cat ${LINK##*/}`
wget "$LINK2/bazy.md5"
FILES=`gawk --posix '/^[0-9a-fA-F]{32}/{gsub("[*\015]", "", $2); print $1 "  " $2}' bazy.md5`
cd ..
rm -rf tmp

echo "$FILES" | gawk "{print \"$LINK2/\" \$2}" | xargs wget

# if it is md5sum which is not verbose by default, then we need to tell it to
# be verbose
MD5SUM_OUT=`echo "d41d8cd98f00b204e9800998ecf8427e  /dev/null" | md5sum -c`
if [ -z "$MD5SUM_OUT" ]; then
  MD5SUM_ADDITIONAL_ARGS=-v
fi

echo "$FILES" | md5sum -c $MD5SUM_ADDITIONAL_ARGS


# vim: ft=sh
