#!/bin/sh
##
## Sets the title of xterm-compatible terminals.
## $Id: settitle,v 1.4 2008/11/08 23:45:57 mina86 Exp $
## By Stanislaw Klekot (dozzie/AT/irc.pl)
## Released to Public Domain
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

if [ $# = 0 ]; then
  echo -ne "\e]2;rxvt\007"
else
  echo -ne "\e]2;$*\007"
fi
