#!/bin/sh
##
## Sets the title of xterm-compatible terminals.
## $Id: settitle,v 1.3 2005/07/11 00:20:58 mina86 Exp $
## By Stanislaw Klekot (dozzie/AT/irc.pl)
## Released to Public Domain
##

if [ $# = 0 ]; then
  echo -ne "\e]2;rxvt\007"
else
  echo -ne "\e]2;$*\007"
fi
