#!/bin/sh
##
## surun - Wrapper running command via su or sudo
## Copyright 2013,2018 by Michal Nazarewicz (mina86@mina86.com)
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

case $1 in --help|-h)
	cat <<EOF
usage: $0 [ <command> <argument> ... ]
Start a root shell (if no command given) or run given command as root.

Use either sudo or su depending on which is available, unless user is already
a super-user at which point calling sudo/su is skipped all together.
EOF
	exit 0
esac

umask 022

if [ $(id -u) -eq 0 ]; then
	if [ $# -eq 0 ]; then
		set -- "${SHELL:-/bin/sh}"
	fi
	exec "$@"
fi

sudo=$(which sudo 2>/dev/null)

if [ $# -eq 0 ]; then
	exec "${sudo:-su}" ${sudo:+-s}
elif [ -n "$sudo" ]; then
	exec "$sudo" "$@"
fi

if test=$(printf %q aoeu\ \'\"\ aoeu 2>/dev/null) &&
   [ x"$test" = x"aoeu\\ \\'\\\"\\ aoeu" ]; then
	escaped=$(printf ' %q' "$@")
else
	escaped=
	for arg; do
		arg=\'$(printf %s "$arg" | sed -e "s/'/'\\\\''/g")\'
		escaped="$escaped $arg"
	done
fi
exec su -c "$escaped"
