#!/usr/bin/perl -l
##
## Prints RGB value of colors given in stdin.
## Copyright (c) 2005 by Stanislaw Klekot (dozzie/AT/irc.pl)
##
## This software is OSI Certified Open Source Software.
## OSI Certified is a certification mark of the Open Source Initiative.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##
## This is part of Tiny Applications Collection
##   -> http://tinyapps.sourceforge.net/
##

open RGB, "/usr/X11R6/lib/X11/rgb.txt";

my %colors = map {
  s/^\s+//; s/\s+$//; $_ = lc $_;
  split /\s+/, $_, 4;
  ($_[3], sprintf "rgb:%02x/%02x/%02x", @_[0 .. 2]);
} grep { !/^\s*!/ } <RGB>;

close RGB;

sub printcolor($) {
  my $color = lc shift;
  if (exists $colors{$color}) {
    print "$color => $colors{$color}";
  } else {
    print "No such color: $color";
  }
}

if (@ARGV) {
  printcolor shift while @ARGV;
  exit;
}

chomp, printcolor $_ while <STDIN>;
