#!/usr/bin/perl -l
##
## Prints RGB value of colors given in stdin.
## $Id: xcolor2rgb,v 1.1 2005/07/10 16:43:55 mina86 Exp $
## Copyright (c) 2005 by Stanislaw Kelkot (dozzie/at/irc.pl)
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##

open RGB, "/usr/X11R6/lib/X11/rgb.txt";

my %colors = map {
  s/^\s+//; s/\s+$//; $_ = lc $_;
  split /\s+/, $_, 4;
  ($_[3], sprintf "rgb:%02x/%02x/%02x", @_[0 .. 2]);
} grep { !/^\s*!/ } <RGB>;

close RGB;

sub printcolor($) {
  my $color = lc shift;
  if (exists $colors{$color}) {
    print "$color => $colors{$color}";
  } else {
    print "No such color: $color";
  }
}

if (@ARGV) {
  printcolor shift while @ARGV;
  exit;
}

chomp, printcolor $_ while <STDIN>;
